#ifndef __BMGRERROR_DEF_H__
#define __BMGRERROR_DEF_H__

#define True 1
#define False 0

typedef enum BlockMgrError {
   BLOCKMGR_OK=0,
   BLOCKMGR_IO_ERR,
   BLOCKMGR_FILE_NOT_FOUND,
   BLOCKMGR_INVALID_MAGIC,
   BLOCKMGR_INT_ERROR,
   BLOCKMGR_BLOCK_TOO_BIG,
   BLOCKMGR_DATA_TOO_BIG,
   BLOCKMGR_INVALID_BLOCK_SIZE,
   BLOCKMGR_NO_MEMORY,
   BLOCKMGR_TRANSAC_EXISTS,
   BLOCKMGR_NO_TRANSAC,
   BLOCKMGR_TRANSAC_REPLAY_FAILED,
   BLOCKMGR_TRANSAC_NOT_COMMITTED,
   BLOCKMGR_CHECKSUM_ERR,
   BLOCKMGR_CORRUPT_DATA,
   BLOCKMGR_LOCK_FAILED,
} BlockMgrError;


#endif
